-- ============================================================================
-- SIAGA — 001_init.sql
-- CREATE TABLE semua tabel inti + index (item audit 3.13)
-- ============================================================================
-- Konsolidasi dari: create_officers_table.sql, create_attendance_table.sql,
-- create_stall_categories_table.sql, create_setoran_table.sql,
-- create_market_config_table.sql, create_announcements_table.sql
--
-- Semua idempoten (IF NOT EXISTS) — aman dijalankan ulang.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. officers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.officers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  market_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_officers_user_id ON public.officers(user_id);
CREATE INDEX IF NOT EXISTS idx_officers_market_id ON public.officers(market_id);

-- ---------------------------------------------------------------------------
-- 2. attendance
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  officer_id UUID NOT NULL,
  market_id BIGINT NOT NULL,
  check_in TIMESTAMPTZ,
  check_out TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attendance_officer_id ON public.attendance(officer_id);
CREATE INDEX IF NOT EXISTS idx_attendance_market_id ON public.attendance(market_id);
CREATE INDEX IF NOT EXISTS idx_attendance_created_at ON public.attendance(created_at);

-- ---------------------------------------------------------------------------
-- 3. stall_categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.stall_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 4. setoran
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.setoran (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  officer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  market_id INTEGER NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
  total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
  transaction_count INTEGER NOT NULL DEFAULT 0,
  note TEXT,
  proof_image_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending_treasurer' CHECK (status IN ('pending_treasurer', 'pending_head', 'approved', 'rejected')),
  rejection_reason TEXT,
  approved_by_treasurer UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_by_head UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at_treasurer TIMESTAMPTZ,
  approved_at_head TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_setoran_officer_id ON public.setoran(officer_id);
CREATE INDEX IF NOT EXISTS idx_setoran_market_id ON public.setoran(market_id);
CREATE INDEX IF NOT EXISTS idx_setoran_status ON public.setoran(status);
CREATE INDEX IF NOT EXISTS idx_setoran_created_at ON public.setoran(created_at DESC);

-- ---------------------------------------------------------------------------
-- 5. market_config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.market_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market_id BIGINT NOT NULL REFERENCES markets(id) ON DELETE CASCADE,
  key VARCHAR(50) NOT NULL,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT market_config_unique_per_market UNIQUE (market_id, key)
);

-- ---------------------------------------------------------------------------
-- 6. announcements
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market_id BIGINT REFERENCES markets(id) ON DELETE CASCADE,
  title VARCHAR(150) NOT NULL,
  content TEXT,
  priority INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  start_date TIMESTAMPTZ DEFAULT NOW(),
  end_date TIMESTAMPTZ,
  created_by INTEGER REFERENCES users(id_user),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_announcements_active
  ON public.announcements (market_id, is_active, start_date, end_date);

-- ============================================================================
-- END 001_init.sql
-- ============================================================================