-- ============================================
-- COMBINED MIGRATION: Retribution Types & Rates
-- ============================================
-- Run this entire script in Supabase SQL Editor

-- STEP 1: Add new columns to retribution_types
ALTER TABLE public.retribution_types 
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS unit TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- STEP 2: Remove old columns from retribution_types
ALTER TABLE public.retribution_types 
  DROP COLUMN IF EXISTS amount,
  DROP COLUMN IF EXISTS market_id;

-- STEP 3: Create retribution_rates table (if not exists)
CREATE TABLE IF NOT EXISTS public.retribution_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  stall_id BIGINT,
  market_id BIGINT NOT NULL,
  types_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- STEP 4: Seed retribution_types
INSERT INTO public.retribution_types (code, name, category, unit, notes, created_at, updated_at) VALUES
('2-005-79', 'Jaspro 2026', 'Retribusi Pedagang', 'Bulanan', 'Bergantung jenis tempat usaha', NOW(), NOW()),
('2-005-80', 'Harian', 'Retribusi Pedagang', 'Harian', 'Per lapak/pedagang per hari', NOW(), NOW()),
('2-005-84', 'Daging', 'Komoditas', 'Harian / per meja', 'Per meja daging atau fasilitas daging', NOW(), NOW()),
('2-005-85', 'Rempah / Tepung / Kelapa', 'Komoditas', 'Harian', 'Per lapak komoditas', NOW(), NOW()),
('2-005-86', 'Cabut Bulu Ayam', 'Fasilitas Pasar', 'Per penggunaan', 'Per penggunaan fasilitas cabut bulu ayam', NOW(), NOW()),
('2-005-87', 'Mobil Box', 'Jasa Kendaraan', 'Per kendaraan', 'Per kendaraan masuk', NOW(), NOW()),
('2-005-88', 'Parkir', 'Jasa Kendaraan', 'Per kendaraan', 'Motor, mobil, atau kendaraan lain', NOW(), NOW()),
('2-005-89', 'Bongkaran', 'Jasa Logistik', 'Per kegiatan', 'Bongkar muat barang', NOW(), NOW()),
('2-005-90', 'Rekomendasi', 'Administrasi', 'Per dokumen', 'Surat rekomendasi', NOW(), NOW()),
('2-005-91', 'Kartu Pedagang', 'Administrasi', 'Per kartu', 'Penerbitan/perpanjangan kartu', NOW(), NOW()),
('2-005-92', 'BBN', 'Pendapatan Lain', 'Sesuai ketentuan', 'Per transaksi', NOW(), NOW()),
('2-005-93', 'Izin Pemasangan Listrik & PDAM', 'Perizinan', 'Per izin', 'Permohonan pemasangan utilitas', NOW(), NOW()),
('2-005-94', 'Penerimaan Lain-lain', 'Lain-lain', 'Variatif', 'Sesuai jenis penerimaan', NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- STEP 5: Seed retribution_rates for all active stalls
INSERT INTO public.retribution_rates (types_id, market_id, stall_id, amount, created_at, updated_at)
SELECT t.id, s.market_id, s.id, 2000, NOW(), NOW()
FROM public.stalls s, public.retribution_types t
WHERE t.code = '2-005-80' AND s.status = 'AKTIF'
ON CONFLICT DO NOTHING;

INSERT INTO public.retribution_rates (types_id, market_id, stall_id, amount, created_at, updated_at)
SELECT t.id, s.market_id, s.id, 10000000, NOW(), NOW()
FROM public.stalls s, public.retribution_types t
WHERE t.code = '2-005-79' AND s.status = 'AKTIF'
ON CONFLICT DO NOTHING;