-- Create attendance table for officer check-in/check-out
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  officer_id UUID NOT NULL,
  market_id BIGINT NOT NULL,
  check_in TIMESTAMPTZ,
  check_out TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_attendance_officer_id ON public.attendance(officer_id);
CREATE INDEX IF NOT EXISTS idx_attendance_market_id ON public.attendance(market_id);
CREATE INDEX IF NOT EXISTS idx_attendance_created_at ON public.attendance(created_at);

-- Enable RLS
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- Policy: Officers can view their own attendance
CREATE POLICY "attendance_officer_select"
ON public.attendance
FOR SELECT
TO authenticated
USING (officer_id = auth.uid());

-- Policy: Officers can insert their own attendance
CREATE POLICY "attendance_officer_insert"
ON public.attendance
FOR INSERT
TO authenticated
WITH CHECK (officer_id = auth.uid());

-- Policy: Officers can update their own attendance
CREATE POLICY "attendance_officer_update"
ON public.attendance
FOR UPDATE
TO authenticated
USING (officer_id = auth.uid())
WITH CHECK (officer_id = auth.uid());

-- Policy: Allow authenticated users to read attendance (no market restriction for simplicity)
CREATE POLICY "attendance_select"
ON public.attendance
FOR SELECT
TO authenticated
USING (true);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_attendance_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_attendance_timestamp ON public.attendance;
CREATE TRIGGER update_attendance_timestamp
BEFORE UPDATE ON public.attendance
FOR EACH ROW
EXECUTE FUNCTION public.update_attendance_timestamp();