-- Create officers table
CREATE TABLE IF NOT EXISTS public.officers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  market_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_officers_user_id ON public.officers(user_id);
CREATE INDEX IF NOT EXISTS idx_officers_market_id ON public.officers(market_id);

-- Enable RLS
ALTER TABLE public.officers ENABLE ROW LEVEL SECURITY;

-- Policy: Officers can view their own profile
CREATE POLICY "officers_select_own"
ON public.officers
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- Policy: Officers can insert their own profile
CREATE POLICY "officers_insert_own"
ON public.officers
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

-- Policy: Officers can update their own profile
CREATE POLICY "officers_update_own"
ON public.officers
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Policy: Allow authenticated read for admin/reporting
CREATE POLICY "officers_select_auth"
ON public.officers
FOR SELECT
TO authenticated
USING (true);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_officers_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_officers_timestamp ON public.officers;
CREATE TRIGGER update_officers_timestamp
BEFORE UPDATE ON public.officers
FOR EACH ROW
EXECUTE FUNCTION public.update_officers_timestamp();