-- Create stall_categories table
CREATE TABLE IF NOT EXISTS public.stall_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert sample categories if none exist
INSERT INTO public.stall_categories (name, description)
VALUES
  ('Sayur-sayuran', 'Kategori untuk penjualan sayur dan buah'),
  ('Kelontong', 'Kategori kebutuhan sehari-hari'),
  ('Daging', 'Kategori daging dan seafood'),
  ('Rempah-rempah', 'Kategori bumbu dan rempah'),
  ('Parkir', 'Kategori layanan parkir')
ON CONFLICT DO NOTHING;