-- Create retribution_rates table for pricing
CREATE TABLE IF NOT EXISTS public.retribution_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  stall_id BIGINT,
  market_id BIGINT NOT NULL,
  types_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT fk_retribution_rates_types FOREIGN KEY (types_id) REFERENCES public.retribution_types(id) ON DELETE CASCADE,
  CONSTRAINT fk_retribution_rates_stall FOREIGN KEY (stall_id) REFERENCES public.stalls(id) ON DELETE SET NULL,
  CONSTRAINT fk_retribution_rates_market FOREIGN KEY (market_id) REFERENCES public.markets(id) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_retribution_rates_types_id ON public.retribution_rates(types_id);
CREATE INDEX IF NOT EXISTS idx_retribution_rates_stall_id ON public.retribution_rates(stall_id);
CREATE INDEX IF NOT EXISTS idx_retribution_rates_market_id ON public.retribution_rates(market_id);

-- Enable RLS
ALTER TABLE public.retribution_rates ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "retribution_rates_select" ON public.retribution_rates;
DROP POLICY IF EXISTS "retribution_rates_insert" ON public.retribution_rates;
DROP POLICY IF EXISTS "retribution_rates_update" ON public.retribution_rates;

-- Policy: Allow all authenticated users to read retribution rates
CREATE POLICY "retribution_rates_select"
ON public.retribution_rates
FOR SELECT
TO authenticated
USING (true);

-- Policy: Allow all authenticated users to insert retribution rates
CREATE POLICY "retribution_rates_insert"
ON public.retribution_rates
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Allow all authenticated users to update retribution rates
CREATE POLICY "retribution_rates_update"
ON public.retribution_rates
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_retribution_rates_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_retribution_rates_timestamp ON public.retribution_rates;
CREATE TRIGGER update_retribution_rates_timestamp
BEFORE UPDATE ON public.retribution_rates
FOR EACH ROW
EXECUTE FUNCTION public.update_retribution_rates_timestamp();